Fix/article list
Axel77g/projet-semestriel-3A-IW pull request #45
Opened 2023-06-30 18:31 UTC by Prumme

2023-07-01 08:43 UTC, Axel77g requested changes

2023-07-01 08:43 UTC, Axel77g commented on www/Controllers/Articles.php
Ilyam a besoin de ce populate pour une de ces pages, c'est normal que ça a été commenté ?? @Prumme

2023-07-01 12:08 UTC, Prumme commented on www/Controllers/Articles.php
La liste ne fonctionne juste pas si le code n'est pas commenté, à moins qu'une partie du code d'ilyam, n'as pas été merge, sans mon changement la liste des article ne s'affiche pas

2023-07-01 13:52 UTC, Axel77g commented on www/Controllers/Articles.php
c'est a cause du script de db 
ça créer une colonne author au lieu de author_id

2023-07-02 18:24 UTC, closed without merging

2023-07-02 18:24 UTC, Prumme commented
Not necessary