Creating the Users panel in backoffice
Axel77g/projet-semestriel-3A-IW pull request #76
Opened 2023-07-15 21:40 UTC by Robiinf

This implements the User-Back feature, empowering administrators with the ability to efficiently manage user accounts. The User-Back feature provides administrators with a comprehensive list of all users, allowing them to easily locate and perform edits or deletions as needed. This enhancement streamlines user administration processes, saving valuable time and improving overall productivity for the organization.

2023-07-15 22:13 UTC, Prumme commented on www/routes.php
> +        // "Permission:admin"
Ce serait surement mieux de mettre la permission admin
On veux pas que n'importe qui de connecter puisse requeter tout nos users

2023-07-15 22:16 UTC, Prumme approved these changes

2023-07-15 22:17 UTC, Prumme commented on www/routes.php
> +        // "Permission:admin"
J'ai modifier direct 👍

2023-07-16 08:54 UTC, Axel77g approved these changes

2023-07-16 08:54 UTC, Axel77g commented on www/Controllers/Auth.php
> +        if($payload['role'] == 'admin'){
Il faudrait vérifié que tu puisses le faire uniquement si tu es connecté et admin, sinon tu peux créer des users admin sans être connecté

2023-07-16 08:54 UTC, Axel77g commented on www/Controllers/Users.php
> +        echo json_encode([
J'ai modifié ça dans ma branche Profil, c'est une modification que tu avais besoin où ?

2023-07-16 08:54 UTC, Axel77g commented on www/Controllers/Users.php
> +        echo json_encode([
J'ai trouver j'ai remplacé dans le fichier en question par response.id, si tu as un id ici c'est que c'est bon

2023-07-16 08:56 UTC, Axel77g requested changes

2023-07-16 08:56 UTC, Axel77g commented on www/Controllers/Auth.php
> +        if($payload['role'] == 'admin'){
il faut changé

2023-07-17 19:19 UTC, Axel77g approved these changes

2023-07-17 19:19 UTC, merged