when / go to Home template
Axel77g/projet-semestriel-3A-IW pull request #81
Opened 2023-07-17 10:30 UTC by Prumme

When router is on / 
go to the slug of home template page

2023-07-17 19:17 UTC, Axel77g requested changes

2023-07-17 19:17 UTC, Axel77g commented on www/Controllers/Pages.php
> +        if($page->getTemplate() == "home" && page::exists(["template" => $page->getTemplate()])){
`page::exists` on est sur que ça marche ça ? c'est quoi la var `page`

2023-07-17 19:17 UTC, Axel77g commented on www/src/js/components/Home.js
> +    router.push(home.path);
du coup tu amène sur /home c'est ça ?

2023-07-17 20:00 UTC, Prumme commented on www/Controllers/Pages.php
> +        if($page->getTemplate() == "home" && page::exists(["template" => $page->getTemplate()])){
Le but c'est de verifier que si on essaie de créer une page (template "home"), on verifie qu'il n'en existe pas une autre ne bdd

et oui ça marche, ça fait bien le blocage si il existe une template "home"

2023-07-17 20:10 UTC, Prumme commented on www/src/js/components/Home.js
> +    router.push(home.path);
J'ai remove ça dans les commit suivant:
J'import désormais le component templates/home/view.js
dans le component Home

2023-07-18 07:42 UTC, Axel77g approved these changes

2023-07-18 07:42 UTC, merged